# Generated by Django 5.2 on 2026-03-31 10:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Market', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_traded_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('total_volume', models.IntegerField(default=0)),
                ('day_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('opening_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market Master',
                'verbose_name_plural': 'Market Masters',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='is_market_maker',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MarketMakerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=2, help_text='Base price for orders. Leave blank to use Last Traded Price.', max_digits=10, null=True)),
                ('spread_pct', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Spread percentage per level (e.g. 1.0 = 1%)', max_digits=5)),
                ('quantity', models.IntegerField(default=100, help_text='Number of shares per order at each level')),
                ('num_levels', models.IntegerField(default=3, help_text='Number of buy/sell price levels to maintain (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_maker', to='trading.user')),
            ],
            options={
                'verbose_name': 'Market Maker Config',
                'verbose_name_plural': 'Market Maker Configs',
            },
        ),
    ]
